apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: 1290950/demo-service:2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
            requests: 
              memory: 256Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
            - name: VENDOR_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: vendor
