apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mongodb-database
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: db-config
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: database-pvc
