name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag demo-service:2
        docker tag demo-service:2 1290950/demo-service:2
        docker login --username 1290950 --password dckr_pat_n4On6E5JujkjS8fjI3TwTwuQ68s
        docker push 1290950/demo-service:2
